import java.util.ArrayList;


/**
 * <h1>Truck</h1> Represents a Truck
 */
public class Truck extends Vehicle {

    private final double GAS_RATE = 1.66;

    /**
     * Default Constructor
     */
    //============================================================================
    public Truck() {
        super(); //not sure
    }
    
    //============================================================================

    /**
     * Constructor
     * 
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight); //not sure
    }
    
    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        double profit = 0;
        for (Package pkg : super.getPackages()) {
            profit = profit + pkg.getPrice() - (getMaxRange() * GAS_RATE);
        }
        return profit;
    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     * 
     * @return Truck Report
     */
    @Override
    public String report() {
        String firstPart = String.format(
                "==========Truck Report========== \n" +
                        "License Plate No.: %s \n" +
                        "Destination: %d \n" +
                        "Weight Load: %.2f/%.2f \n" +
                        "Net Profit: $%.2f \n" +
                        "=====Shipping Labels===== \n",
                getLicensePlate(), getZipDest(), getCurrentWeight(), getMaxWeight(), getProfit());
        String secondPart = "";
        for (Package pkg : getPackages()) {
            secondPart += pkg.shippingLabel() + "\n";
        }
        String lastPart = "==============================";
    	return firstPart + secondPart + lastPart;
    }



}